### ISSUE TITLE
Design a logo 

### ISSUE THREAD

**Issue by lukas-mertens** [nix-basement/nix-basement#16]
We should design a logo to make the appearance of the project more professional. The logo should somehow be relatable to the nixos-logo: https://upload.wikimedia.org/wikipedia/commons/c/c4/NixOS_logo.svg Additionally, as nix-basement provides a base-framework and a few other components around it, I think it would be a nice idea to somehow incorporate the design of a house in there and highlight the basement. Then we can later make a second variation of the logo in which we highlight different parts of the building, for example a room or the roof representing a different component in the framework.

**Comment by Lainika** [comment]
Hi @lukas-mertens,
I did some thinking and clicked something together in Illustrator.
It's all quite similar though. On the left you can see in 2 variants. The approach with the different floors.
On the right side different color variations. 
Is there something that would fit for you?
If what is there let me know and I make it ready and a PR to it.
If it is desired otherwise. I am also happy to listen.
![Nix_Basement](https://user-images.githubusercontent.com/79374825/198896558-4ec97e0a-edc9-427a-8851-9ee023cc7131.PNG)

**Comment by lukas-mertens** [comment]
Thanks, that's very nice! I like it. We will vote in the team which is best so that you can create a PR and have it counted for hacktoberfest.

**Comment by lukas-mertens** [comment]
Hi @Lainika we discussed a bit about the logo and came to the conclusion that the left column is the one we like most. Just one thing: Could you tidy it up a bit? Here are a few examples of places where the spacing between elements doesn't quite line up.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/10901304/198901452-88f3b16a-ffe5-4db8-894a-e6a305a046d0.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/10901304/198901493-4cadc703-a1c4-4ae5-91ce-c49db5d59d66.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/10901304/198901567-85448e05-de37-45fb-9153-6df11d4ea0df.png">
The spacing should follow a consistent concept and things should be aligned consistently and precisely. Is it possible for you to change those things?

**Comment by Lainika** [comment]
Sure no problem. 
I have times bereingte versions made.
Is also a white darkmode version desired?
![Nix_Basement_Logo](https://user-images.githubusercontent.com/79374825/198905030-e9fe5bd0-fca9-49a4-8e82-b56f61de267c.svg)
![Nix_Basement_Logo_Roof](https://user-images.githubusercontent.com/79374825/198905032-5f4262a3-0be3-4fb9-9573-004d80ccdd4a.svg)
![Nix_Basement_Logo_Room](https://user-images.githubusercontent.com/79374825/198905033-796ca272-938f-42a8-a6aa-aa27a146998c.svg)
![Nix_Basement_Logo_Basement](https://user-images.githubusercontent.com/79374825/198905034-eb6435b8-0138-4837-987b-203af89d3817.svg)

**Comment by lukas-mertens** [comment]
Looks great! A darkmode version would be great, so that we have it at hand, when we need it. Especially for the landingpage it might be needed. Thanks a lot, you can do a PR if you want to!
